// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Ng1ZD0yuXsRO_ZO5ahMNvhxUt8W_nrI',
    appId: '1:852996766026:web:aaa11d953a7d8d88f929b3',
    messagingSenderId: '852996766026',
    projectId: 'appotp-c6980',
    authDomain: 'appotp-c6980.firebaseapp.com',
    storageBucket: 'appotp-c6980.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMXGKTJ5ToVaKyQDUwlKlmVjDT5nM-T8',
    appId: '1:852996766026:android:9af450de0dc1eba1f929b3',
    messagingSenderId: '852996766026',
    projectId: 'appotp-c6980',
    storageBucket: 'appotp-c6980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZu1rAdITHUC5RspKwoPTvwb4C0-rC76U',
    appId: '1:852996766026:ios:29372ec039602df8f929b3',
    messagingSenderId: '852996766026',
    projectId: 'appotp-c6980',
    storageBucket: 'appotp-c6980.appspot.com',
    iosClientId: '852996766026-qsrdvhaasm728tpo17dtk7ie1s0r8gj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZu1rAdITHUC5RspKwoPTvwb4C0-rC76U',
    appId: '1:852996766026:ios:84e31a736b84b724f929b3',
    messagingSenderId: '852996766026',
    projectId: 'appotp-c6980',
    storageBucket: 'appotp-c6980.appspot.com',
    iosClientId: '852996766026-s1tdf99l18ah25j3psam2an2o3erndg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpPhone.RunnerTests',
  );
}
